<?xml version="1.0"?>
<robot name="follower_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <!-- Property definitions -->
    <xacro:property name="base_width" value="0.35"/>
    <xacro:property name="base_length" value="0.45"/>
    <xacro:property name="base_height" value="0.15"/>
    <xacro:property name="wheel_radius" value="0.08"/>
    <xacro:property name="wheel_width" value="0.04"/>
    <xacro:property name="wheel_separation_length" value="0.30"/>

    <!-- Base link -->
    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <material name="blue">
                <color rgba="0 0 1 1"/>
            </material>
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="5.0"/>
            <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1"/>
        </inertial>
    </link>

    <!-- Wheel Macro -->
    <xacro:macro name="wheel" params="prefix suffix x_reflect y_reflect">
        <link name="${prefix}_${suffix}_wheel">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
                </geometry>
                <material name="black">
                    <color rgba="0 0 0 1"/>
                </material>
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
                </geometry>
            </collision>
            <inertial>
                <mass value="0.5"/>
                <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01"/>
            </inertial>
        </link>

        <joint name="${prefix}_${suffix}_wheel_joint" type="continuous">
            <parent link="base_link"/>
            <child link="${prefix}_${suffix}_wheel"/>
            <origin xyz="${x_reflect*wheel_separation_length/2} ${y_reflect*(base_width/2 + wheel_width/2)} 0" rpy="${pi/2} 0 0"/>
            <axis xyz="0 0 1"/>
        </joint>

        <gazebo reference="${prefix}_${suffix}_wheel">
            <material>Gazebo/Black</material>
            <mu1>1.0</mu1>
            <mu2>1.0</mu2>
        </gazebo>
    </xacro:macro>

    <!-- Create wheels -->
    <xacro:wheel prefix="front" suffix="left"  x_reflect="1" y_reflect="1" />
    <xacro:wheel prefix="front" suffix="right" x_reflect="1" y_reflect="-1" />
    <xacro:wheel prefix="rear"  suffix="left"  x_reflect="-1" y_reflect="1" />
    <xacro:wheel prefix="rear"  suffix="right" x_reflect="-1" y_reflect="-1" />

    <!-- Camera link -->
    <link name="camera_link">
        <visual>
            <geometry>
                <box size="0.05 0.05 0.05"/>
            </geometry>
            <material name="black">
                <color rgba="0 0 0 1"/>
            </material>
        </visual>
    </link>

    <!-- Camera joint -->
    <joint name="camera_joint" type="fixed">
        <parent link="base_link"/>
        <child link="camera_link"/>
        <origin xyz="${base_length/2} 0 ${base_height + 0.1}" rpy="-0.1 0 0"/>
    </joint>

    <!-- Gazebo materials -->
    <gazebo reference="base_link">
        <material>Gazebo/Blue</material>
        <mu1>0.2</mu1>
        <mu2>0.2</mu2>
    </gazebo>

    <!-- Gazebo plugin -->
    <gazebo>
        <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
            <!-- Left -->
            <leftJoint>front_left_wheel_joint</leftJoint>
            <leftJoint>rear_left_wheel_joint</leftJoint>
            <!-- Right -->
            <rightJoint>front_right_wheel_joint</rightJoint>
            <rightJoint>rear_right_wheel_joint</rightJoint>
            
            <wheelSeparation>${base_width}</wheelSeparation>
            <wheelDiameter>${2*wheel_radius}</wheelDiameter>
            <robotBaseFrame>base_link</robotBaseFrame>
            <commandTopic>cmd_vel</commandTopic>
            <odometryTopic>odom</odometryTopic>
            <odometryFrame>odom</odometryFrame>
            <robotNamespace>/</robotNamespace>
            <publishWheelTF>true</publishWheelTF>
            <publishWheelJointState>true</publishWheelJointState>
            <publishOdomTF>true</publishOdomTF>
            <odometrySource>world</odometrySource>
            <updateRate>50.0</updateRate>
            <wheelAcceleration>1.0</wheelAcceleration>
            <wheelTorque>20.0</wheelTorque>
            <rosDebugLevel>Debug</rosDebugLevel>
            <legacyMode>false</legacyMode>
        </plugin>
    </gazebo>

    <!-- Camera plugin -->
    <gazebo reference="camera_link">
        <sensor type="depth" name="camera">
            <update_rate>20</update_rate>
            <camera>
                <horizontal_fov>1.047198</horizontal_fov>
                <image>
                    <width>640</width>
                    <height>480</height>
                    <format>R8G8B8</format>
                </image>
                <clip>
                    <near>0.05</near>
                    <far>3.0</far>
                </clip>
            </camera>
            <plugin name="camera_controller" filename="libgazebo_ros_openni_kinect.so">
                <baseline>0.2</baseline>
                <alwaysOn>true</alwaysOn>
                <updateRate>20.0</updateRate>
                <cameraName>camera</cameraName>
                <frameName>camera_link</frameName>
                <imageTopicName>rgb/image_raw</imageTopicName>
                <depthImageTopicName>depth/image_raw</depthImageTopicName>
                <pointCloudTopicName>depth/points</pointCloudTopicName>
                <cameraInfoTopicName>rgb/camera_info</cameraInfoTopicName>
                <depthImageCameraInfoTopicName>depth/camera_info</depthImageCameraInfoTopicName>
                <pointCloudCutoff>0.4</pointCloudCutoff>
                <hackBaseline>0.07</hackBaseline>
                <distortionK1>0.0</distortionK1>
                <distortionK2>0.0</distortionK2>
                <distortionK3>0.0</distortionK3>
                <distortionT1>0.0</distortionT1>
                <distortionT2>0.0</distortionT2>
            </plugin>
        </sensor>
    </gazebo>
</robot>
