<?xml version="1.0" encoding="ASCII"?>
<robot name="leader_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <!-- Property definitions -->
    <xacro:property name="base_width" value="0.35"/>
    <xacro:property name="base_length" value="0.45"/>
    <xacro:property name="base_height" value="0.15"/>
    <xacro:property name="wheel_radius" value="0.08"/>
    <xacro:property name="wheel_width" value="0.04"/>

    <!-- Base link -->
    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <material name="red">
                <color rgba="1 0 0 1"/>
            </material>
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="5.0"/>
            <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1"/>
        </inertial>
    </link>

    <!-- Left wheel -->
    <link name="left_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
            <material name="black">
                <color rgba="0 0 0 1"/>
            </material>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="0.5"/>
            <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01"/>
        </inertial>
    </link>

    <!-- Right wheel -->
    <link name="right_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
            <material name="black">
                <color rgba="0 0 0 1"/>
            </material>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="0.5"/>
            <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01"/>
        </inertial>
    </link>

    <!-- Left wheel joint -->
    <joint name="left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel"/>
        <origin xyz="0 ${base_width/2 + wheel_width/2} 0" rpy="${pi/2} 0 0"/>
        <axis xyz="0 0 1"/>
    </joint>

    <!-- Right wheel joint -->
    <joint name="right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel"/>
        <origin xyz="0 ${-base_width/2 - wheel_width/2} 0" rpy="${pi/2} 0 0"/>
        <axis xyz="0 0 1"/>
    </joint>

    <!-- Gazebo materials -->
    <gazebo reference="base_link">
        <material>Gazebo/Red</material>
        <mu1>0.2</mu1>
        <mu2>0.2</mu2>
    </gazebo>

    <gazebo reference="left_wheel">
        <material>Gazebo/Black</material>
        <mu1>1.0</mu1>
        <mu2>1.0</mu2>
    </gazebo>

    <gazebo reference="right_wheel">
        <material>Gazebo/Black</material>
        <mu1>1.0</mu1>
        <mu2>1.0</mu2>
    </gazebo>

    <!-- Gazebo plugin -->
    <gazebo>
        <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
            <leftJoint>left_wheel_joint</leftJoint>
            <rightJoint>right_wheel_joint</rightJoint>
            <wheelSeparation>${base_width}</wheelSeparation>
            <wheelDiameter>${2*wheel_radius}</wheelDiameter>
            <robotBaseFrame>base_link</robotBaseFrame>
            <publishWheelTF>true</publishWheelTF>
            <publishWheelJointState>true</publishWheelJointState>
            <commandTopic>leader/cmd_vel</commandTopic>
            <odometryTopic>leader/odom</odometryTopic>
            <odometryFrame>leader/odom</odometryFrame>
            <updateRate>50</updateRate>
            <wheelAcceleration>1.0</wheelAcceleration>
            <wheelTorque>20</wheelTorque>
            <publishOdomTF>true</publishOdomTF>
            <odometrySource>world</odometrySource>
            <rosDebugLevel>Debug</rosDebugLevel>
            <legacyMode>false</legacyMode>
            <alwaysOn>true</alwaysOn>
            <updateRate>100.0</updateRate>
            <torque>20</torque>
            <robotNamespace>/</robotNamespace>
        </plugin>
    </gazebo>
</robot>
